import { ESLintRules } from "../types"

export const autofix: ESLintRules = {
  "@typescript-eslint/ban-types": "warn",
  "@typescript-eslint/no-array-constructor": "warn",
  "@typescript-eslint/no-empty-interface": "warn",
  "@typescript-eslint/no-inferrable-types": "warn",
  "@typescript-eslint/prefer-namespace-keyword": "warn",
  "@typescript-eslint/type-annotation-spacing": "warn",
  "no-var": "warn",
  "prefer-const": "warn",
  "no-extra-boolean-cast": "warn",
  "no-extra-semi": "warn",
  "no-regex-spaces": "warn",
  "no-unused-labels": "warn",
  "dot-location": "warn",
  "eqeqeq": "warn",
  "new-parens": "warn",
  "no-extra-bind": "warn",
  "no-extra-label": "warn",
  "no-useless-computed-key": "warn",
  "no-useless-rename": "warn",
  "no-whitespace-before-property": "warn",
  "rest-spread-spacing": "warn",
  "strict": "warn",
  "unicode-bom": "warn",
  "import/first": "warn",
  "arrow-body-style": "warn",
  "arrow-parens": "warn",
  "arrow-spacing": "warn",
  "generator-star-spacing": "warn",
  "no-confusing-arrow": "warn",
  "jsdoc/check-param-names": "warn",
  "jsdoc/check-tag-names": "warn",
  "jsdoc/no-types": "warn",
  "unicorn/new-for-builtins": "warn",
  "unicorn/no-array-instanceof": "warn",
  "unicorn/no-new-buffer": "warn",
  "unicorn/throw-new-error": "warn",
  "sort-imports": "warn",
  "linebreak-style": "warn",
  "no-div-regex": "warn",
  "no-unneeded-ternary": "warn",
  "@typescript-eslint/consistent-type-definitions": "warn",
  "import/order": "warn",
  "import/newline-after-import": "warn"
}
