import { Linter } from "eslint"

interface ESLintRules {
  [name: string]: Linter.RuleLevel | Linter.RuleLevelAndOptions
}

const MAX_COMPLEXITY = 11

// This is the extract generated by diffing the eslint config result
// from *best practises* and *errors* to our base config.
export const essential: ESLintRules = {
  "array-callback-return": [
    "error",
    {
      allowImplicit: true
    }
  ],
  "block-scoped-var": "error",
  complexity: [ "warn", MAX_COMPLEXITY ],
  "consistent-return": "warn",
  curly: [ "error", "multi-line" ],
  "dot-notation": [
    "error",
    {
      allowKeywords: true,
      allowPattern: ""
    }
  ],
  eqeqeq: [ "error", "smart" ],
  "getter-return": [
    "error",
    {
      allowImplicit: true
    }
  ],
  "guard-for-in": "error",
  "no-alert": "warn",
  "no-await-in-loop": "error",
  "no-extra-parens": [
    "off",
    "all",
    {
      conditionalAssign: true,
      nestedBinaryExpressions: false,
      returnAssign: false,
      ignoreJSX: "all",
      enforceForArrowConditionals: false
    }
  ],
  "no-floating-decimal": "error",
  "no-global-assign": [
    "error",
    {
      exceptions: []
    }
  ],
  "no-implicit-coercion": [
    "off",
    {
      boolean: false,
      number: true,
      string: true,
      allow: []
    }
  ],
  "no-magic-numbers": [
    "warn",
    {
      ignore: [ 0, 1, 2, 10 ],
      ignoreArrayIndexes: true,
      enforceConst: true,
      detectObjects: false
    }
  ],
  "no-multi-spaces": [
    "error",
    {
      ignoreEOLComments: false
    }
  ],
  "no-new": "error",
  "no-proto": "error",
  "no-restricted-properties": [
    "error",
    {
      object: "arguments",
      property: "callee",
      message: "arguments.callee is deprecated"
    },
    {
      object: "global",
      property: "isFinite",
      message: "Please use Number.isFinite instead"
    },
    {
      object: "self",
      property: "isFinite",
      message: "Please use Number.isFinite instead"
    },
    {
      object: "window",
      property: "isFinite",
      message: "Please use Number.isFinite instead"
    },
    {
      object: "global",
      property: "isNaN",
      message: "Please use Number.isNaN instead"
    },
    {
      object: "self",
      property: "isNaN",
      message: "Please use Number.isNaN instead"
    },
    {
      object: "window",
      property: "isNaN",
      message: "Please use Number.isNaN instead"
    },
    {
      property: "__defineGetter__",
      message: "Please use Object.defineProperty instead."
    },
    {
      property: "__defineSetter__",
      message: "Please use Object.defineProperty instead."
    },
    {
      object: "Math",
      property: "pow",
      message: "Use the exponentiation operator (**) instead."
    }
  ],
  "no-return-assign": [ "error", "always" ],
  "no-return-await": "error",
  "no-self-assign": [
    "error",
    {
      props: false
    }
  ],
  "no-useless-return": "error",
  "no-void": "error",
  "prefer-promise-reject-errors": [
    "error",
    {
      allowEmptyReject: true
    }
  ],
  radix: "error",
  strict: [ "error", "never" ],
  "valid-typeof": [
    "error",
    {
      requireStringLiterals: true
    }
  ],
  "vars-on-top": "error",
  "wrap-iife": [
    "error",
    "outside",
    {
      functionPrototypeMethods: false
    }
  ],
  yoda: "error"
}

export const es2015: ESLintRules = {
  "arrow-body-style": [
    "error",
    "as-needed",
    {
      requireReturnForObjectLiteral: false
    }
  ],
  // Note: Disabled to align with prettier config
  // "arrow-parens": [
  //   "error",
  //   "as-needed",
  //   {
  //     "requireForBlockBody": true
  //   }
  // ],
  "arrow-spacing": [
    "error",
    {
      before: true,
      after: true
    }
  ],
  "generator-star-spacing": [
    "error",
    {
      before: false,
      after: true
    }
  ],
  "no-confusing-arrow": [
    "error",
    {
      "allowParens": true
    }
  ],
  "no-useless-constructor": "error",
  "no-var": "error",
  "object-shorthand": [
    "error",
    "always",
    {
      ignoreConstructors: false,
      avoidQuotes: true
    }
  ],
  "prefer-arrow-callback": [
    "warn",
    {
      allowNamedFunctions: false,
      allowUnboundThis: true
    }
  ],
  "prefer-const": [
    "warn",
    {
      destructuring: "any",
      ignoreReadBeforeAssign: true
    }
  ],
  "prefer-destructuring": [
    "warn",
    {
      VariableDeclarator: {
        array: false,
        object: true
      },
      AssignmentExpression: {
        array: true,
        object: true
      }
    },
    {
      enforceForRenamedProperties: false
    }
  ],
  "prefer-numeric-literals": "error",
  "prefer-rest-params": "warn",
  "prefer-spread": "warn",
  "prefer-template": "warn",
  "symbol-description": "error",
  "template-curly-spacing": "error",
  "yield-star-spacing": [ "error", "after" ]
}

export const imports: ESLintRules = {
  // Note: Disabled as it conflicts with some typical HOC usage.
  // 'import/no-named-as-default': 'error',

  "import/no-named-as-default-member": "error",
  "import/no-duplicates": "error",
  "import/no-mutable-exports": "error",
  "import/no-absolute-path": "error",
  "import/no-dynamic-require": "error",
  "import/no-named-default": "error",
  "import/no-self-import": "error",
  "import/no-useless-path-segments": "error"
}

export const node: ESLintRules = {
  // require all requires be top-level
  // https://eslint.org/docs/rules/global-require
  "global-require": "error",

  // disallow use of the Buffer() constructor
  // https://eslint.org/docs/rules/no-buffer-constructor
  "no-buffer-constructor": "error",

  // disallow use of new operator with the require function
  "no-new-require": "error",

  // disallow string concatenation with __dirname and __filename
  // https://eslint.org/docs/rules/no-path-concat
  "no-path-concat": "error"
}

export const variables: ESLintRules = {
  // Note: Disabled as existing code is not following this convention.
  // Is also more style related not functional in ES6/TS environments.
  // disallow declaration of variables already declared in the outer scope
  // 'no-shadow': 'error',

  // disallow use of undefined when initializing variables
  "no-undef-init": "error"

  // Note: Disabled as existing code is not following this convention.
  // Is also more style related not functional in ES6/TS environments.
  // disallow use of variables before they are defined
  // 'no-use-before-define': [
  //   'error',
  //   { functions: true, classes: true, variables: true },
  // ],
}

export const react: ESLintRules = {
  "jsx-quotes": [ "error", "prefer-double" ],

  "react/jsx-no-target-blank": [
    "error",
    {
      enforceDynamicLinks: "always"
    }
  ],

  "jsx-a11y/label-has-associated-control": [ "error" ],

  "react/jsx-closing-bracket-location": [ "error", "line-aligned" ],
  "react/jsx-closing-tag-location": "error",
  "react/jsx-curly-spacing": [
    "error",
    "never",
    {
      allowMultiline: true
    }
  ],
  "react/jsx-equals-spacing": [ "error", "never" ],
  "react/jsx-first-prop-new-line": [ "error", "multiline-multiprop" ],
  "react/jsx-indent": [ "error", 2 ],
  "react/jsx-indent-props": [ "error", 2 ],
  "react/jsx-max-props-per-line": [
    "error",
    {
      maximum: 1,
      when: "multiline"
    }
  ],
  "react/jsx-one-expression-per-line": [
    "error",
    {
      allow: "single-child"
    }
  ],
  "react/jsx-props-no-multi-spaces": "error",
  "react/jsx-tag-spacing": [
    "error",
    {
      closingSlash: "never",
      beforeSelfClosing: "always",
      afterOpening: "never",
      beforeClosing: "never"
    }
  ],
  "react/jsx-wrap-multilines": [
    "error",
    {
      declaration: "parens-new-line",
      assignment: "parens-new-line",
      return: "parens-new-line",
      arrow: "parens-new-line",
      condition: "parens-new-line",
      logical: "parens-new-line",
      prop: "parens-new-line"
    }
  ],
  "react/self-closing-comp": "error",

  "react/forbid-prop-types": [
    "error",
    {
      forbid: [ "any", "array", "object" ],
      checkContextTypes: true,
      checkChildContextTypes: true
    }
  ],
  "react/jsx-boolean-value": [
    "error",
    "never",
    {
      always: []
    }
  ],
  "react/jsx-no-bind": [
    "error",
    {
      ignoreRefs: true,
      allowArrowFunctions: true,
      allowFunctions: false,
      allowBind: false,
      ignoreDOMComponents: true
    }
  ],
  "react/no-danger": "warn",
  "react/no-did-update-set-state": "error",
  "react/no-will-update-set-state": "error",
  "react/prefer-es6-class": [ "error", "always" ],
  "react/prefer-stateless-function": [
    "warn",
    {
      ignorePureComponents: true
    }
  ],
  "react/no-unused-prop-types": [
    "error",
    {
      customValidators: [],
      skipShapeProps: true
    }
  ],
  "react/no-array-index-key": "error",
  "react/require-default-props": [
    "error",
    {
      forbidDefaultForRequired: true
    }
  ],
  "react/void-dom-elements-no-children": "error",
  "react/default-props-match-prop-types": [
    "error",
    {
      allowRequiredDefaults: false
    }
  ],
  "react/no-redundant-should-component-update": "error",
  "react/no-unused-state": "error",
  "react/jsx-curly-brace-presence": [
    "error",
    {
      props: "never",
      children: "never"
    }
  ],
  // Disabled as this is just style and nothing which produces any issues.
  // 'react/destructuring-assignment': ['error', 'always'],
  "react/no-access-state-in-setstate": "error",
  "react/button-has-type": [
    "error",
    {
      button: true,
      submit: true,
      reset: false
    }
  ],
  "react/no-this-in-sfc": "error",
  "jsx-a11y/lang": "error"
}
